apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gh-runner-webhook
  namespace: core-app
spec:
  template:
    spec:   
      image: summerwind/actions-runner-dind-rootless:ubuntu-22.04
      dockerdWithinRunnerContainer: true  
      organization: VFGroup-MyVodafone-OnePlatform
      group: OnePlatform
      labels:
       - gh-runner-webhook
      ephemeral: true
      resources:
        limits:
          cpu: 1024m
          memory: 2Gi
        requests:
          cpu: 1024m
          memory: 2Gi
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: gh-runner-webhook-autoscaler
  namespace: core-app
spec:
  scaleTargetRef:
    kind: RunnerDeployment
    name: gh-runner-webhook
  scaleDownDelaySecondsAfterScaleOut: 60
  minReplicas: 1
  maxReplicas: 5
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "30m"
