githubWebhookServer:
  enabled: true
  secret:
    create: true
    enabled: true
    name: github-webhook-server # value of the secret passed with the pwgen
  


  ingress:
    annotations:
      alb.ingress.kubernetes.io/actions.ssl-redirect: >-
        {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port":
        "443", "StatusCode": "HTTP_301"}}
      alb.ingress.kubernetes.io/group.name: core-single-lb
      alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/group.order: "2"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/healthcheck-path: /login
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/target-type: ip
    enabled: true
    hosts:
      - host: testbot.oneplatform.vodafone.com
        http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: oneplatform-testbot
                port:
                  number: 8080



githubEnterpriseServerURL: https://github.vodafone.com 
runnerGithubURL: https://github.vodafone.com 
githubURL: https://github.vodafone.com/api/v3 
githubUploadURL: https://github.vodafone.com/api/v3
authSecret:
  name: controller-manager-webhook # auth controller with github
